#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate 考前衝刺 280 關鍵知識點 markdown from curated CA DRE associations."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "考前衝刺_280關鍵知識點.md"

# (章節, 看到, 選／記, 一句陷阱或對照)
# Target: exactly 280 rows
ITEMS: list[tuple[str, str, str, str]] = []


def add(section: str, see: str, choose: str, tip: str = "") -> None:
    ITEMS.append((section, see, choose, tip))


# ========== 1. 權利束／土地特性／價值 ==========
S = "01 權利束、土地特性與價值（DUST）"
add(S, "Bundle of rights／權利束", "佔有、使用收益、排除、處分、控制（受 PETE 限制）", "沒有絕對豁免政府警察權")
add(S, "PETE", "Police／Eminent Domain／Taxation／Escheat", "四大公權力")
add(S, "DUST（價值四要素）", "Demand＋Utility＋Scarcity＋Transferability", "不是 indestructibility")
add(S, "Cloud on title／產權烏雲", "缺 Transferability（可轉讓性）", "不是缺 utility")
add(S, "Immobility／Indestructibility／Non-homogeneity", "土地三大物理特性", "malleability 不是")
add(S, "Situs", "地利／理想區位偏好 → Location", "不是 illiquidity、通膨")
add(S, "Assemblage", "合併相鄰地塊的「行為／過程」", "Plottage 才是合併後增值")
add(S, "Plottage", "合併後整體價值 > 分開加總", "過程叫 assemblage")
add(S, "Accession", "自然或人為附加物歸土地所有人", "含 accretion 等")
add(S, "Accretion", "淤積使土地增加", "Reliction＝水面退卻露出新陸")
add(S, "Erosion／Avulsion", "侵蝕漸失／突發沖刷喪失", "Avulsion 通常不立刻改地界")
add(S, "Principle of regression", "高價屋被低價鄰房「往下拉」", "Progression 相反")
add(S, "Principle of progression", "低價屋被高價鄰房「往上帶」", "Regression 相反")
add(S, "Market value", "典型條件下理論最可能成交價", "Market price＝實際成交價")
add(S, "Assessed value", "課稅用評估價（County Assessor）", "Prop 13 限制加州漲幅")
add(S, "Stigmatized property", "心理／社會污名壓價（非物理瑕疵）", "兇案傳聞≠結構損壞")

# ========== 2. 不動產 vs 動產／定著物 ==========
S = "02 不動產、動產、定著物與 MARIA"
add(S, "Real property", "土地＋定著物＋附屬權利", "未砍立木仍是不動產")
add(S, "Personal property／Chattel", "可移動物、未固定建材", "鬆散鋪石未鋪＝動產")
add(S, "Severance", "不動產分離成動產（砍樹）", "不是 annexation")
add(S, "Annexation", "動產附著成定著物", "MARIA 測試")
add(S, "MARIA", "Method／Adaptability／Relationship／Intention／Agreement", "契約沉默時 Intention 最關鍵")
add(S, "Trade fixture", "商業租客營業設備＝動產，租期前可拆", "須修復損害")
add(S, "Appurtenance", "附隨土地移轉（地役權、建物、礦權等）", "契據未寫也常隨移轉")
add(S, "Emblements／Fructus industriales", "耕作農作物收益（勞動收益）", "天然樹木＝fructus naturales")
add(S, "Encroachment", "實體越界＝持續 trespass", "不是 easement")

# ========== 3. 產權型態 ==========
S = "03 產權型態（Freehold／Leasehold）"
add(S, "Fee simple absolute", "最高完整所有權，可立遺囑繼承", "Life estate 不能 will 給子女")
add(S, "Fee simple determinable", "違條件→產權「自動」歸還", "so long as／until")
add(S, "Fee simple subject to condition subsequent", "違條件→須「上法院」取回（Right of re-entry）", "不會自動歸還")
add(S, "Life estate", "以權利人壽命為限，死亡終止", "不可立遺囑傳子女")
add(S, "Pur autre vie", "以「第三人」壽命衡量的終身產權", "for the life of another")
add(S, "Estate for years", "固定起迄日，到期自動結束", "不必通知終止")
add(S, "Periodic estate／period to period", "按月／按週自動續約，須通知才停", "Month-to-month")
add(S, "Estate at will", "雙方可隨時終止的隨意租賃", "較少書面固定期")
add(S, "Estate／Tenancy at sufferance", "租期滿仍佔用（holdover）", "房東尚未同意或驅離")
add(S, "Leasehold 四類型", "Years／Period／Will／Sufferance", "Freehold 不是租賃")

# ========== 4. 地役權／許可／負擔 ==========
S = "04 地役權、許可權、留置權"
add(S, "License（許可）", "個人特權、通常可撤銷、不跑隨土地", "口頭停車常是 license")
add(S, "Appurtenant easement", "附屬地役權，跑隨土地，通常須書面", "需役地＋供役地")
add(S, "Easement in gross", "個人／公司地役權（如公用事業）", "通常不附屬某需役地")
add(S, "Easement by prescription", "公開、敵意、持續使用達法定年限", "類似時效")
add(S, "Easement by necessity", "土地封鎖時通行必要", "常因分割產生")
add(S, "Dominant／Servient tenement", "需役地／供役地", "供役地負擔通行")
add(S, "Mechanic's lien", "施工未付款之技工留置權", "限制處分直到清償")
add(S, "Voluntary encumbrance", "如 deed of trust／mortgage", "減損未負擔淨值")
add(S, "Deed restriction／CC&Rs", "私人限制「如何使用」土地", "發起者是私人／開發商")
add(S, "Zoning vs deed restriction", "兩者衝突→遵「最嚴格」", "不是永遠公法勝／最寬鬆")
add(S, "種族／宗教限制公約", "無法執行＋違法（Fair Housing）", "地契本身通常仍有效")
add(S, "Deed restriction 違法時", "條款無效，不影響所有權／deed", "不會自動 revert")

# ========== 5. 代理與委託類型 ==========
S = "05 代理關係與 Listing 類型"
add(S, "Listing agreement", "Customer→Client，成立 listing agent", "最佳用書面")
add(S, "Exclusive right-to-sell／Authorization", "誰賣出都付全額佣金（含屋主自售）", "最保障經紀人")
add(S, "Exclusive agency", "只找一家，但屋主自售可免佣", "Audrey／Janelle 題型")
add(S, "Open listing", "多家競爭，須證明 Procuring cause", "自售常免佣")
add(S, "Net listing", "賣方定淨得，超額歸經紀人", "加州合法但高風險須充分揭露")
add(S, "Procuring cause", "不中斷促成鏈→拿佣金依據", "Open listing 關鍵")
add(S, "Protection／Safety period", "到期後一定期間內賣給曾帶看買家仍付佣", "防過河拆橋")
add(S, "Extinction of subject matter", "房屋毀損→listing 終止", "龍捲風／火災")
add(S, "Performance（終止代理）", "最理想：成交履約完成", "優於 revocation／expiration")
add(S, "Dual agency", "同時代理買賣雙方", "須同意與揭露")
add(S, "Fiduciary duties", "忠誠、服從（合法）、注意、會計、揭露等", "不服從違法指示")
add(S, "Ostensible agency／Agency by estoppel", "言行讓第三人誤信有代理＋未澄清", "事後不得否認")
add(S, "BRBC（C.A.R.）", "預設非專屬買方代理", "不必勾選才變非專屬")
add(S, "NAR 會員佣金糾紛仲裁", "一方要求→通常強制仲裁", "須全體書面才可放棄")
add(S, "Agency 受何法管轄", "Agency law ＋ Contract law", "衝突時代理法常優先")

# ========== 6. 契約基礎 ==========
S = "06 契約法基礎"
add(S, "Bilateral contract", "雙方互為承諾（買賣約典型）", "promise for promise")
add(S, "Unilateral contract", "承諾換行為（懸賞）", "找到才付錢")
add(S, "Implied contract", "由行為成立（攔計程車）", "非 express／written")
add(S, "Express contract", "口頭或書面明確約定", "")
add(S, "Executory", "已簽但尚未完全履約（簽約到 closing）", "Executed＝已全部完成")
add(S, "Executed contract", "雙方義務已全部履行", "交屋過戶後")
add(S, "Void", "自始無效", "Voidable＝可選擇撤銷")
add(S, "Offer 何時變合約", "Offeree 接受＋通知送達 Offeror", "僅簽名未送達不夠")
add(S, "撤回要約期限", "接受通知送達前可 rescind", "接受後不能當要約撤回")
add(S, "Counteroffer", "拒絕原要約＋提出新要約", "原要約死亡")
add(S, "多份報價時已發 counter", "先撤回舊 counter 再回新 offer", "防一屋賣兩人")
add(S, "Earnest money", "善意誠意金／定金", "非契約成立必要對價")
add(S, "Valuable consideration", "足夠且適當的對價", "空頭白話可能不足")
add(S, "Specific performance", "強制交付特定不動產", "因土地唯一性")
add(S, "Liquidated damages", "常＝賣方可扣留誠意金", "買方無故違約")
add(S, "Rescission", "解除契約、回復原狀", "不是強迫交屋")
add(S, "死亡對契約", "通常遺產承受；個人服務契約例外", "Listing 常屬個人服務")
add(S, "Statute of Frauds", "多數不動產合約須書面", "≤1 年租約口頭可有效")
add(S, "9-month lease", "可不書面", "18-month 須書面")
add(S, "電子簽名", "當事人同意即可用於 RE 合約", "E-SIGN／UETA")
add(S, "Doctrine of laches", "拖延過久致對方受損→衡平救濟被拒", "即使訴訟時效未過")
add(S, "Parol evidence rule", "原則限制用口頭改完整書面合約", "")
add(S, "Inspection contingency", "檢查不合格可解約／談判", "屋頂漏水題")
add(S, "Appraisal contingency", "估價不足可走", "賣方市場加此條款較不具競爭力")
add(S, "Finance contingency", "貸款不成可走", "")
add(S, "Contingency 本質", "條件成就前可保護一方退出", "Addendum≠退出權本身")

# ========== 7. 揭露與加州表格 ==========
S = "07 揭露義務、TDS、NHD、Lead"
add(S, "Material fact", "會改變買賣決策／出價的事實→必須揭露", "As-is 不能免")
add(S, "As-is（加州）", "不願修繕，但仍須填 TDS、揭露已知重大瑕疵", "常見迷思")
add(S, "TDS", "1–4 住宅賣方已知屋況揭露", "不含學區資訊")
add(S, "TDS 親送晚交", "買方通常 3 天可取消", "郵寄／電子常 5 天")
add(S, "Foreclosure／REO", "常豁免填 TDS", "銀行不知屋況")
add(S, "NHD", "揭露是否在洪患／火災／地震等災害區", "不是石棉／鉛的專用表")
add(S, "Lead-based paint", "Pre-1978 強制聯邦揭露", "1964 建＝要揭露鉛")
add(S, "Latent defect", "常規看屋難發現的隱性瑕疵", "乾壁後石棉")
add(S, "Patent defect", "明顯可見瑕疵", "")
add(S, "HIV/AIDS 前住戶", "禁止揭露（公平住房／隱私）", "遵從不揭露＝合法")
add(S, "死亡揭露（加州）", "通常近 3 年內須考量；6 年前自然死亡常不必", "Civil Code 相關")
add(S, "Megan's Law／性罪犯", "合約標準提示即可；經紀人不必主動調查披露", "不是物業物理重大事實同等義務")
add(S, "賣方要求隱瞞瑕疵", "拒絕＋仍須向買方揭露／可終止委託", "服從不法指示會共同負責")
add(S, "油漆掩蓋地基裂縫", "必須揭露，否則 misrepresentation", "不是叫他漆更好")
add(S, "RPA（C.A.R.）", "常用住宅買賣約，但州政府未強制頒布唯一表", "非 promulgated statewide")
add(S, "買賣約當事人", "Buyer ＋ Seller", "Broker 不是合約當事人")

# ========== 8. 公平住房與偏見 ==========
S = "08 公平住房與職業倫理"
add(S, "Implicit bias", "無意識刻板印象差別服務", "自認公平卻假設有色人種買便宜房")
add(S, "Explicit bias", "明知故犯歧視（拒服務同性伴侶）", "")
add(S, "Steering", "依族群導向特定社區", "違法")
add(S, "Blockbusting", "恐嚇社區變動促拋售", "違法")
add(S, "Redlining", "依地區／族群拒貸", "違法")
add(S, "Ethics vs Morals", "Ethics＝外部團體標準化；Morals＝個體內心", "NAR Code of Ethics")
add(S, "缺專業領域能力", "提供服務「之前」須揭露", "NAR Article 11")
add(S, "Commingling", "個人資金與客戶信託金混合", "Conversion＝挪用花掉")
add(S, "Appraisal fee 依估值加減", "不道德／違反 USPAP", "費不能掛鉤估出來的價值")
add(S, "DRE", "加州執照監管機關", "C.A.R.／NAR 是協會非執法")
add(S, "Real Estate Commissioner", "DRE 首長", "")
add(S, "交易文件保存", "結案起至少 3 年", "2022/6/20 → 2025/6/20")

# ========== 9. 估價／CMA ==========
S = "09 估價、CMA 與三大方法"
add(S, "Appraisal", "僅持牌估價師可做正式估價", "須符合 USPAP")
add(S, "CMA", "不需估價師執照", "非正式意見")
add(S, "BPO", "經紀人價格意見，低於正式 appraisal", "")
add(S, "Sales comparison／Market data", "中古屋最常用", "")
add(S, "Cost approach", "新成屋／特殊建築首選", "土地＋重建成本－折舊")
add(S, "Income approach", "收益性物業", "IRV")
add(S, "CMA 選 comp", "同社區＋近 6–12 月＋至少約 3 筆", "25 英里太遠")
add(S, "調整方向", "永遠調 Comp，不調 Subject", "Comp 少衛浴→加價")
add(S, "Farm area／Farming", "深耕特定地理區域成專家", "不是真的務農；也非全市撒網")
add(S, "Listing price", "初始要價 Asking price", "≠最終成交價")

# ========== 10. 收益法公式 ==========
S = "10 收益法與投資指標（IRV）"
add(S, "PGI", "100% 滿租理想總收入", "未扣空置")
add(S, "EGI", "PGI－空置／呆帳＋其他收入（未扣營業費用）", "")
add(S, "NOI", "EGI－營業費用＝營運淨利", "通常不含貸款本息與所得稅")
add(S, "Cap rate", "NOI ÷ Value", "IRV：I＝R×V")
add(S, "Value（收益法）", "NOI ÷ Cap rate", "先年化月 NOI×12")
add(S, "月 NOI $10,000、cap 6%", "年 NOI $120,000 → Value $2,000,000", "別直接用月 NOI 去除")
add(S, "NOI $25,000／售價 $500,000", "Cap＝5%", "不是 10%／20%")
add(S, "投資人要扣日常費用後利潤", "看 NOI", "不是 PGI／EGI")
add(S, "只要收入扣空置、不問費用", "看 EGI", "")
add(S, "Cap rate 高", "通常風險較高／價值相對較低", "反之亦然")

# ========== 11. 融資與抵押 ==========
S = "11 融資、抵押與信託契據"
add(S, "Trustor", "借款人（設定信託）", "-OR 給出權利")
add(S, "Trustee", "受託人持名義產權", "")
add(S, "Beneficiary", "貸款機構", "-EE 收受")
add(S, "Mortgagor", "借款人／抵押人", "Mortgagee＝銀行")
add(S, "Optionor", "給出選擇權的一方（通常賣方）", "Optionee＝買方")
add(S, "Grantor／Grantee", "讓與人／受讓人", "")
add(S, "LTV", "貸款額÷價值", "高 LTV 常需 PMI")
add(S, "PMI", "傳統貸款高 LTV 的抵押保險", "")
add(S, "Qualifying ratios", "Payment-to-income ＋ Debt-to-income", "不是 LTV")
add(S, "Interest-only 月息", "本金×利率÷12", "$140k×4.9%÷12＝$571.67")
add(S, "Amortized loan 月利息", "依「剩餘本金」計息", "前期利息多")
add(S, "緊縮貨幣市場", "利率↑、點數／開辦費↑", "不是更便宜")
add(S, "資金供給增加", "利率↓", "")
add(S, "Sale-leaseback 優勢", "租金可當營業費用抵稅", "")
add(S, "RESPA 違規", "因轉介付回扣／kickback", "如 title 公司付錢轉介")
add(S, "TILA／Truth in Lending", "揭露真實借貸成本", "不決定利率升降")

# ========== 12. 契據與產權移轉 ==========
S = "12 契據、產權與告知"
add(S, "Grant deed（加州常用）", "含兩項默示保證（未移轉給他人、未設定未揭露負擔）", "")
add(S, "Quitclaim deed", "轉讓「現有任何權利」，幾乎無保證", "清雲／放棄權利常用")
add(S, "Warranty deed", "保證最多（六大契約）", "視州而異")
add(S, "Bargain and sale", "暗示持有可轉讓權，保證少", "")
add(S, "Habendum clause", "“to have and to hold” 定義權利範圍", "")
add(S, "Granting clause", "表明移轉意圖的核心句", "")
add(S, "Delivery and acceptance", "契據生效必要：交付＋接受", "只簽名不夠")
add(S, "Recording", "產生 Constructive notice", "")
add(S, "Actual notice", "親身／直接知悉", "")
add(S, "Constructive notice", "推定應查公共紀錄而知", "")
add(S, "Abstract of title", "產權檢索後的歷史摘要報告", "不是 title plant")
add(S, "Title plant", "產權公司資料庫設施", "")
add(S, "Marketable title", "無重大負擔／瑕疵、可安心轉售", "清 significant encumbrances")
add(S, "Chain of title", "產權移轉連鎖", "")
add(S, "Legal description", "足以唯一區辨的法定描述", "≠街道地址")
add(S, "Reservation／Exception", "契據保留權利或載明既有 easement", "")
add(S, "Probate", "遺產認證／法庭程序", "Testate＝有遺囑；Intestate＝無")
add(S, "Adverse possession", "公開敵意佔用達年限可取得所有權", "")
add(S, "Dedication／Public grant", "私人捐地給政府／公地撥給私人", "")

# ========== 13. 土地測量描述 ==========
S = "13 土地測量與面積"
add(S, "Metes and bounds", "從 POB 沿方位距離繞回；度分秒", "有 landmark／benchmark")
add(S, "Government／Rectangular survey", "Township、Range、Section、Meridian", "T2S R2W")
add(S, "Lot and block／Recorded plat", "分區圖地號", "")
add(S, "1 acre", "43,560 sq ft", "2 acres＝87,120")
add(S, "Section", "通常 640 acres", "1 mile×1 mile")

# ========== 14. 租賃與物業管理 ==========
S = "14 租賃、房東房客與物管"
add(S, "Assignment", "受讓人常直接付租金給房東", "")
add(S, "Sublease／Sublet", "次承租人付租金給原租客", "Blithe→Earnest")
add(S, "Gross lease", "租客付固定租金，房東付多數費用", "")
add(S, "Net lease", "租客另付稅／保險／維護等", "")
add(S, "Percentage lease", "底租＋營業額抽成", "零售常見")
add(S, "Step-up／Graduated lease", "租金按階段調升", "")
add(S, "Unlawful detainer", "房東合法驅離訴訟", "禁止私自換鎖斷水電")
add(S, "Constructive eviction", "房東違法迫使無法居住", "違法")
add(S, "Security deposit（加州現制常考）", "上限常考「最多約一個月租金」取向", "題庫若寫 one month 依最新法複核")
add(S, "押金明細與退還時限", "常見考點：搬出後約 21 天內明細／退還", "依現行 Civil Code 複核")
add(S, "農藥定期使用", "房東須通知租客", "")
add(S, "Property management", "代管出租換報酬的職業", "")
add(S, "Typical lease 不含", "未來買斷選擇權（那是 lease-option）", "期長、標的描述、簽名才是基本")

# ========== 15. 環境危害 ==========
S = "15 環境危害"
add(S, "Friable", "石棉易捏碎粉化→纖維飛散", "≠ asbestosis（病名）")
add(S, "Asbestos", "天然礦物纖維絕緣材料，吸入傷肺", "≠ radon／CFCs／lead")
add(S, "Radon", "無色無味放射性氣體，經地基裂縫進入", "鈾衰變")
add(S, "Lead", "舊油漆／水管；Pre-1978", "")
add(S, "UFFI", "脲甲醛泡沫絕緣", "")
add(S, "CFCs", "舊冷媒／空調含氯氟碳", "")
add(S, "HVAC", "Heating, Ventilation, Air Conditioning", "H≠Home")
add(S, "Wastewater lines", "把水排離住宅的管線", "City water＝進水")

# ========== 16. 住房類型與市場 ==========
S = "16 住宅類型、市場與專業"
add(S, "Custom home", "買家先確定＋依規格訂製", "")
add(S, "Spec／Speculative home", "無特定買家先建再賣", "")
add(S, "Tract home", "標準化模型大量開發", "")
add(S, "Warehouse", "工業地產", "不是 farm／純 commercial 零售")
add(S, "Industrial", "倉儲、製造、物流", "")
add(S, "大型雇主進駐小鎮", "人口↑需求↑供給相對緊→房價↑", "")
add(S, "供給增加", "價格傾向下跌", "")
add(S, "Specialization", "多數人可用多種方式專精", "不一定要換照")
add(S, "REIT 優點", "股份流動性高如股票", "相對直接持房報酬可能較低")
add(S, "Office building 最高租金", "通常 Class A", "")
add(S, "最準估值產品", "Appraisal", "高於 CMA／BPO")
add(S, "NAR Code of Ethics", "引導 REALTOR® 日常倫理", "非政府執法機關")

# ========== 17. Escrow／結案／雜項高頻 ==========
S = "17 Escrow、結案與高頻雜項"
add(S, "Escrow holder（加州）", "特定人可在無獨立 escrow 執照下任託管（有例外資格）", "依題選合資格者")
add(S, "Closing", "結案過戶完成", "其前合約多為 executory")
add(S, "Title insurance", "保障產權風險", "")
add(S, "Mineral rights 優先", "礦權人可合理進入地表開採（非重大惡意破壞）", "Surface 不當然優先")
add(S, "Quiet enjoyment", "不受前權利人騷擾等，非「不能有噪音」", "不能用來排除合法礦權")
add(S, "Holographic will", "須親筆書寫；不能只簽 X", "墨水顏色非重點")
add(S, "MLS", "聯賣系統／平台，非法律上的 listing 契約類型", "Open／Exclusive 才是契約類型")
add(S, "Ready, willing and able buyer", "常構成 procuring cause／賺佣基礎", "")
add(S, "Unit-in-place／sq ft／quantity survey", "成本法估建造成本的方法→屬 Appraising", "")
add(S, "Prorations", "結案時稅／租金等按日拆分", "")

# ========== 18. -OR/-EE 與配對陷阱 ==========
S = "18 -OR／-EE 配對速記"
add(S, "看見 -OR", "給出／發起權利的一方", "Grantor, Optionor, Mortgagor, Trustor, Lessor, Vendor")
add(S, "看見 -EE", "收受權利的一方", "Grantee, Optionee, Mortgagee, Trustee/Beneficiary 視脈絡, Lessee, Vendee")
add(S, "錯誤配對常見陷阱", "Optionor＝買方（錯！應為賣方給權）", "考 INCORRECT pairing")
add(S, "Lessor／Lessee", "房東／房客", "")
add(S, "Vendor／Vendee", "分期契據賣方／買方", "")

# ========== 19. 更多題庫高頻對照 ==========
S = "19 題庫高頻對照（一看到就選）"
add(S, "看見「無論誰帶來買方都有佣」", "Exclusive right-to-sell", "")
add(S, "看見「屋主自己賣可免佣、但仍獨家一家」", "Exclusive agency", "")
add(S, "看見「多家經紀＋促成者才有佣」", "Open listing", "")
add(S, "看見「底價以上全歸經紀」", "Net listing", "")
add(S, "看見「必須上法院才能拿回房」+違條件", "Condition subsequent", "")
add(S, "看見「so long as／自動歸還」", "Determinable", "")
add(S, "看見「month-to-month＋須通知」", "Periodic tenancy", "")
add(S, "看見「到期賴著不走」", "Sufferance", "")
add(S, "看見「口頭免費停車可撤」", "License", "")
add(S, "看見「25 miles 的 comp」", "太遠＝不良 comp", "")
add(S, "看見「新成屋估價」", "Cost approach", "")
add(S, "看見「商業收益樓估價」", "Income approach", "")
add(S, "看見「比較近期成交」", "Sales comparison", "")
add(S, "看見「Pre-1978／1964」", "Lead disclosure", "")
add(S, "看見「地基裂縫＋氡」", "Radon 進入途徑", "")
add(S, "看見「易捏碎粉化」", "Friable（石棉特性）", "不是選 asbestosis")
add(S, "看見「估價費隨估得價值加收」", "不道德／不行", "")
add(S, "看見「現況出售免揭露？」", "錯！仍要 TDS", "")
add(S, "看見「誠意金是合約必要？」", "錯！非必要，只是善意", "")
add(S, "看見「買方違約最常見結果」", "賣方扣留 earnest money", "")
add(S, "看見「一屋兩 counter」", "先撤回再接受", "")
add(S, "看見「轉租租金付給誰」", "原租客（lessee）", "")
add(S, "看見「文件保存多久」", "3 年", "")
add(S, "看見「≤12 個月租約」", "口頭可能有效", "")
add(S, "看見「法拍屋 TDS」", "常豁免", "")
add(S, "看見「學區寫在 TDS？」", "不包含", "")
add(S, "看見「性罪犯要主動查報？」", "不要；標準提示即可", "")
add(S, "看見「代理最好怎麼建」", "In writing", "")
add(S, "看見「要約何時拘束」", "接受已傳達", "")
add(S, "看見「反要約本質」", "殺舊要約＋新要約", "")
add(S, "看見「合併地塊行為」", "Assemblage", "")
add(S, "看見「合併後溢價」", "Plottage", "")
add(S, "看見「高價屋在低價區」", "Regression", "")
add(S, "看見「產權瑕疵難賣」", "Transferability", "")
add(S, "看見「心理污名房」", "Stigmatized", "")
add(S, "看見「滿租理想收入」", "PGI", "")
add(S, "看見「扣空置後、未扣費用」", "EGI", "")
add(S, "看見「扣營業費用後」", "NOI", "")
add(S, "看見「I / R / V」", "Income＝Rate×Value", "")
add(S, "看見「月 NOI 陷阱」", "先 ×12 再除 cap", "")
add(S, "看見「誰做法正 appraisal」", "Licensed appraiser only", "")
add(S, "看見「CMA 要不要照」", "不需要估價師執照", "")
add(S, "看見「客戶叫你隱瞞」", "不從＋仍揭露", "")
add(S, "看見「隱性偏見」", "無意識刻板假設", "")
add(S, "看見「資金混帳戶」", "Commingling", "")
add(S, "看見「花掉客戶錢」", "Conversion", "")
add(S, "看見「NAR 缺專長」", "服務前揭露", "")
add(S, "看見「Ethic／Moral」", "外規 vs 內心", "")
add(S, "看見「DRE 首長」", "Commissioner", "")
add(S, "看見「監管執照」", "DRE（非 C.A.R.）", "")
add(S, "看見「POB＋度分秒繞回」", "Metes and bounds", "")
add(S, "看見「T／R／Section」", "Government survey", "")
add(S, "看見「quitclaim」", "放棄／移轉現有權、無保證", "")
add(S, "看見「recording」", "Constructive notice", "")
add(S, "看見「title search 報告」", "Abstract of title", "")
add(S, "看見「to have and to hold」", "Habendum", "")
add(S, "看見「delivery & acceptance」", "Deed 生效要件", "")
add(S, "看見「holdover 未同意」", "Sufferance", "")
add(S, "看見「驅離要告」", "Unlawful detainer", "")
add(S, "看見「租金階梯調升」", "Step-up／Graduated", "")
add(S, "看見「HVAC」", "暖氣通風空調", "")
add(S, "看見「排水管」", "Wastewater lines", "")
add(S, "看見「倉庫分類」", "Industrial", "")
add(S, "看見「客製宅」", "Custom home", "")
add(S, "看見「先建無買家」", "Spec home", "")
add(S, "看見「量產模型屋」", "Tract home", "")
add(S, "看見「地理深耕」", "Farming／Farm area", "")
add(S, "看見「最準估值」", "Appraisal", "")
add(S, "看見「流動性優於直持房」", "REIT 優勢", "")
add(S, "看見「保護期條款」", "Protection period", "")
add(S, "看見「標的滅失」", "Extinction of subject matter", "")
add(S, "看見「懈怠原則」", "Laches", "")
add(S, "看見「強制履行」", "Specific performance", "")
add(S, "看見「雙邊承諾」", "Bilateral", "")
add(S, "看見「行為成立契約」", "Implied", "")
add(S, "看見「签约未交屋」", "Executory", "")
add(S, "看見「交屋完成」", "Executed", "")
add(S, "看見「選擇權給出方」", "Optionor（賣方）", "")
add(S, "看見「借款設定信託」", "Trustor", "")
add(S, "看見「質押借款人」", "Mortgagor", "")
add(S, "看見「緊縮市場貸款」", "成本與利率上升", "")
add(S, "看見「轉介拿回扣」", "RESPA 違規", "")
add(S, "看見「售後租回抵稅」", "租金費用化", "")
add(S, "看見「親筆遺囑不能」", "只簽 X", "")
add(S, "看見「MLS 是不是 listing 契約」", "不是（是系統）", "")
add(S, "看見「權利束絕對？」", "否，受 PETE", "")
add(S, "看見「營業定著物拆否」", "租期前可拆（修損害）", "")
add(S, "看見「越界牆」", "Encroachment", "")
add(S, "看見「私人 vs 分區衝突」", "最嚴格者適用", "")
add(S, "看見「禁止某種族購買」", "無效不可執行", "")
add(S, "看見「歧視限制與 deed」", "限制廢、deed 仍有效", "")
add(S, "看見「买方代理預設非專屬」", "BRBC", "")
add(S, "看見「會員仲裁一方要」", "進入仲裁", "")
add(S, "看見「估價不足條款」", "Appraisal contingency", "")
add(S, "看見「檢查不合格可走」", "Inspection contingency", "")
add(S, "看見「3 天取消 TDS」", "親送", "5 天多為郵電")
add(S, "看見「礦權 vs 地表」", "礦權優先（合理開採）", "")
add(S, "看見「DUST」", "Demand Utility Scarcity Transferability", "")
add(S, "看見「課稅價」", "Assessed value", "")
add(S, "看見「理論市價」", "Market value", "")
add(S, "看見「實際成交價」", "Market price", "")
add(S, "看見「調整 comp 少一衛」", "Comp 售價＋衛浴價值", "")
add(S, "看見「新屋成本法」", "Cost approach", "")
add(S, "看見「書面代理最佳」", "In writing", "")
add(S, "看見「客戶資金混合」", "Commingling", "")
add(S, "看見「21 天押金」", "搬出後明細／處理時限考點", "以現行法為準")
add(S, "看見「payment + DTI ratios」", "Qualifying ratios", "")
add(S, "看見「interest-only 月付」", "年息÷12", "")
add(S, "看見「POB 繞一圈」", "Metes and bounds", "")
add(S, "看見「township range」", "政府測量系統", "")
add(S, "看見「acre」", "43,560 sq ft", "")
add(S, "看見「pur autre vie」", "第三人壽命終身產權", "")
add(S, "看見「right of re-entry」", "Condition subsequent＋須訴訟", "")
add(S, "看見「自動終止條件產權」", "Fee simple determinable", "")
add(S, "看見「可立遺囑傳子女」", "Fee simple absolute", "")
add(S, "看見「Life estate 能否 will」", "不能", "")
add(S, "看見「次租客租金」", "付給原租客", "")
add(S, "看見「受讓租金」", "常直接付給房東", "")
add(S, "看見「friable vs asbestosis」", "特性 vs 疾病", "")
add(S, "看見「radon 入口」", "地基裂縫", "")
add(S, "看見「lead 年份」", "1978", "")
add(S, "看見「as-is + TDS」", "仍要完成 TDS", "")
add(S, "看見「material fact」", "影響決策→必揭露", "")
add(S, "看見「latent」", "隱藏難查", "")
add(S, "看見「patent」", "明顯可見", "")
add(S, "看見「stigmatized」", "心理因素壓價", "")
add(S, "看見「situs」", "區位偏好", "")
add(S, "看見「regression」", "好房被差鄰拉低", "")
add(S, "看見「progression」", "差房被好鄰拉高", "")
add(S, "看見「assemblage／plottage」", "行為／溢價", "")
add(S, "看見「accession」", "附加歸所有人", "")
add(S, "看見「appurtenance」", "隨地走", "")
add(S, "看見「trade fixture」", "可拆營業設備", "")
add(S, "看見「MARIA」", "Intention 常為最終關鍵", "")
add(S, "看見「PETE」", "四大公權力", "")
add(S, "看見「bundle of rights」", "權益組合非絕對", "")
add(S, "看見「executory／executed」", "履約中／已完成", "")
add(S, "看見「bilateral／unilateral」", "雙諾／單諾換行為", "")
add(S, "看見「implied」", "行為成約", "")
add(S, "看見「counteroffer」", "拒舊提新", "")
add(S, "看見「earnest money」", "善意金非要件", "")
add(S, "看見「specific performance」", "強制交特定屋", "")
add(S, "看見「laches」", "拖延失權", "")
add(S, "看見「statute of frauds」", "多數要書面；短租例外", "")
add(S, "看見「e-sign」", "同意即有效", "")
add(S, "看見「procuring cause」", "促成鏈", "")
add(S, "看見「protection period」", "到期後保護佣金", "")
add(S, "看見「exclusive right／agency／open／net」", "全佣／自售免／促成／超額", "")
add(S, "看見「commingling／conversion」", "混合／挪用", "")
add(S, "看見「DRE／Commissioner」", "監管／首長", "")
add(S, "看見「TDS／NHD／Lead」", "屋況／災害區／1978前鉛", "")
add(S, "看見「NOI／EGI／PGI／Cap」", "淨利／有效總／潛在總／率", "")
add(S, "看見「cost／income／sales」", "新屋／收益／比較", "")
add(S, "看見「quitclaim／grant／warranty」", "無保／加州常用有限保／最多保", "")
add(S, "看見「constructive／actual notice」", "推定知／親身知", "")
add(S, "看見「metes／gov survey／lot block」", "邊界／網格／地號", "")
add(S, "看見「sufferance／periodic／years」", "賴著／自動續／定期", "")
add(S, "看見「unlawful detainer」", "合法驅離之訴", "")
add(S, "看見「HVAC／wastewater／friable／radon」", "空調系統／排水／石棉易碎／氡", "")
add(S, "看見「custom／spec／tract」", "訂製／投機先建／量產", "")
add(S, "看見「farming」", "區域深耕", "")
add(S, "看見「implicit bias」", "隱性刻板", "")
add(S, "看見「optionor≠buyer」", "給權方是賣方", "")
add(S, "看見「月 NOI 算價值」", "×12 再 ÷ cap", "")
add(S, "看見「3 年文件」", "Broker 保存期限", "")
add(S, "看見「親送 TDS 3 天」", "取消權時限", "")
add(S, "看見「一屋兩約風險」", "先撤 counter", "")
add(S, "看見「轉租付誰」", "原租客", "")
add(S, "看見「礦權優先」", "合理開採可進地表", "")
add(S, "看見「as-is 迷思」", "不能免揭露", "")
add(S, "看見「學區不在 TDS」", "勿選學區資訊", "")
add(S, "看見「性罪犯」", "不須經紀人主動查報", "")
add(S, "看見「AIDS 隱私」", "禁止揭露", "")
add(S, "看見「估價費掛鉤價值」", "禁止", "")
add(S, "看見「CMA 執照」", "不需要", "")
add(S, "看見「正式 appraisal 執照」", "需要估價師", "")
add(S, "看見「BRBC 預設」", "非專屬", "")
add(S, "看見「仲裁一方要求」", "進入仲裁", "")
add(S, "看見「最理想終止代理」", "Performance", "")
add(S, "看見「標的滅失終止」", "Extinction", "")
add(S, "看見「書面最佳代理」", "In writing", "")
add(S, "看見「合約當事人」", "買賣方", "")
add(S, "看見「RPA 是否州頒唯一」", "否", "")
add(S, "看見「缺專長何時說」", "服務前", "")
add(S, "看見「ethics／morals」", "外規／內心", "")
add(S, "看見「緊縮市場」", "貸款變貴", "")
add(S, "看見「資金變多」", "利率下降", "")
add(S, "看見「RESPA」", "禁轉介回扣", "")
add(S, "看見「sale-leaseback」", "租金費用化優勢", "")
add(S, "看見「MLS」", "系統非契約類型", "")
add(S, "看見「holographic will」", "不能只畫 X", "")
add(S, "看見「acre sq ft」", "43560", "")
add(S, "看見「qualifying ratios」", "PTI＋DTI", "")
add(S, "看見「interest only」", "本金×利率÷12", "")
add(S, "最後口訣：定義題", "先對專有名詞原文，再排除故事干擾", "")
add(S, "最後口訣：情境題", "抓「誰／何時／何義務／何例外」四問", "")
add(S, "最後口訣：計算題", "先年化、先調 comp、先確認單位", "")
add(S, "最後口訣：揭露題", "As-is≠免揭露；隱私≠必揭", "")
add(S, "最後口訣：代理佣金題", "Right-to-sell／Agency／Open／Net 四表", "")


def main() -> None:
    # trim or pad to 280
    items = ITEMS[:]
    if len(items) > 280:
        items = items[:280]
    elif len(items) < 280:
        raise SystemExit(f"Need 280 items, got {len(items)}")

    lines: list[str] = []
    lines.append("# 加州 DRE 業務員考試｜考前衝刺 280 關鍵知識點")
    lines.append("")
    lines.append("> 用法：左欄「看到什麼」→ 右欄「選／記什麼」。括號內為常見陷阱對照。")
    lines.append(">")
    lines.append("> 資料來源摘要自本站題庫一／二／三（含 LV17 與 Level 延伸）及常見加州考點整理，供記憶聯想，正式應試請以現行法規與考綱為準。")
    lines.append("")
    lines.append(f"**共 {len(items)} 點**｜建議：每天刷 40 點 × 7 天，考前再掃錯題標記。")
    lines.append("")

    current = None
    n = 0
    for section, see, choose, tip in items:
        if section != current:
            current = section
            lines.append("")
            lines.append(f"## {section}")
            lines.append("")
            lines.append("| # | 看到… | 選／記… | 陷阱／對照 |")
            lines.append("|---:|:---|:---|:---|")
        n += 1
        tip_cell = tip if tip else "—"
        # escape pipes
        see = see.replace("|", "／")
        choose = choose.replace("|", "／")
        tip_cell = tip_cell.replace("|", "／")
        lines.append(f"| {n} | {see} | {choose} | {tip_cell} |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## 30 秒速記卡（考前最後一頁）")
    lines.append("")
    lines.append("1. **Listing 四兄弟**：Right-to-sell（全佣）／Agency（自售免）／Open（促成）／Net（超額）")
    lines.append("2. **租賃四兄弟**：Years／Periodic／Will／Sufferance")
    lines.append("3. **收益三階**：PGI → EGI → NOI → ÷Cap＝Value（月 NOI 先×12）")
    lines.append("4. **估價三法**：比較（中古）／成本（新屋）／收益（投資）")
    lines.append("5. **揭露三表**：TDS（屋況）／NHD（災害區）／Lead（1978前）")
    lines.append("6. **As-is ≠ 免揭露**；**AIDS／性罪犯**通常不主動揭；**客戶叫隱瞞＝拒絕**")
    lines.append("7. **-OR 給、-EE 收**；Optionor 是賣方不是買方")
    lines.append("8. **Deed 衝突跟最嚴**；種族宗教限制＝無效")
    lines.append("9. **接受要送達**；**Counter 先撤再收**；**Specific performance＝要那棟屋**")
    lines.append("10. **Friable≠Asbestosis**；**Radon＝地基縫**；**3年存檔**；**親送TDS＝3天**")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(items)} points -> {OUT}")

    # Keep the website data export in sync with the curated markdown source.
    from export_cram_web import main as export_web

    export_web()


if __name__ == "__main__":
    main()
